# Generated by Django 4.2.1 on 2023-06-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200)),
                ('postalCode', models.CharField(blank=True, max_length=7)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('deleted', models.BooleanField(blank=True, default=0)),
                ('deletedBy', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=15)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('companyPhone', models.CharField(blank=True, max_length=25)),
                ('companyNotes', models.CharField(blank=True, max_length=500)),
                ('deleted', models.BooleanField(blank=True, default=0)),
                ('deletedBy', models.BigIntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(blank=True, max_length=50)),
                ('firstName', models.CharField(blank=True, max_length=50)),
                ('celphone', models.CharField(blank=True, max_length=25)),
                ('workphone', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('deleted', models.BooleanField(blank=True, default=0)),
                ('deletedBy', models.BigIntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.address')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.company')),
            ],
        ),
    ]
