# Generated by Django 4.2.1 on 2023-06-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='deletedBy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='deletedBy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deletedBy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='deleted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='deleted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='deleted',
            field=models.BooleanField(),
        ),
    ]
