# Generated by Django 4.2.1 on 2023-06-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_address_deletedby_company_deletedby_person_deletedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='deleted',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='deleted',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='deleted',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
