# Generated by Django 4.2.4 on 2023-09-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
