# Generated by Django 4.2.4 on 2023-09-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_post_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ext',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='shortName',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
